# Use Node 20
FROM node:20

WORKDIR /app

# Copy package files and install
COPY package*.json ./
RUN npm install

# Copy the rest of the code
COPY . .

# Expose port
EXPOSE 3000

# Start Vite dev server
CMD ["npm", "start"]
